/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _publicLayoutIndexRouteImport } from './routes/__publicLayout/index'
import { Route as _publicLayoutAuthRegisterIndexRouteImport } from './routes/__publicLayout/auth/register/index'
import { Route as _publicLayoutAuthLoginIndexRouteImport } from './routes/__publicLayout/auth/login/index'

const _publicLayoutIndexRoute = _publicLayoutIndexRouteImport.update({
  id: '/__publicLayout/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicLayoutAuthRegisterIndexRoute =
  _publicLayoutAuthRegisterIndexRouteImport.update({
    id: '/__publicLayout/auth/register/',
    path: '/auth/register/',
    getParentRoute: () => rootRouteImport,
  } as any)
const _publicLayoutAuthLoginIndexRoute =
  _publicLayoutAuthLoginIndexRouteImport.update({
    id: '/__publicLayout/auth/login/',
    path: '/auth/login/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof _publicLayoutIndexRoute
  '/auth/login/': typeof _publicLayoutAuthLoginIndexRoute
  '/auth/register/': typeof _publicLayoutAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof _publicLayoutIndexRoute
  '/auth/login': typeof _publicLayoutAuthLoginIndexRoute
  '/auth/register': typeof _publicLayoutAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__publicLayout/': typeof _publicLayoutIndexRoute
  '/__publicLayout/auth/login/': typeof _publicLayoutAuthLoginIndexRoute
  '/__publicLayout/auth/register/': typeof _publicLayoutAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/login/' | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/login' | '/auth/register'
  id:
    | '__root__'
    | '/__publicLayout/'
    | '/__publicLayout/auth/login/'
    | '/__publicLayout/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _publicLayoutIndexRoute: typeof _publicLayoutIndexRoute
  _publicLayoutAuthLoginIndexRoute: typeof _publicLayoutAuthLoginIndexRoute
  _publicLayoutAuthRegisterIndexRoute: typeof _publicLayoutAuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__publicLayout/': {
      id: '/__publicLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _publicLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__publicLayout/auth/register/': {
      id: '/__publicLayout/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof _publicLayoutAuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__publicLayout/auth/login/': {
      id: '/__publicLayout/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof _publicLayoutAuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _publicLayoutIndexRoute: _publicLayoutIndexRoute,
  _publicLayoutAuthLoginIndexRoute: _publicLayoutAuthLoginIndexRoute,
  _publicLayoutAuthRegisterIndexRoute: _publicLayoutAuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
